name: Wave Installer Check

on:
  push:
    branches:
      - main
      - 3.x
  pull_request:
    branches: [ main ]

jobs:
  test-installer:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Create test directory
      run: mkdir project_folder

    - name: Download tarball of current commit
      run: |
        TARBALL_URL=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      https://api.github.com/repos/${{ github.repository }}/tarball/${{ github.sha }} \
                      -I | grep -i "location:" | cut -d " " -f 2 | tr -d '\r')
        curl -L -o wave.tar.gz $TARBALL_URL

    - name: Extract tarball to test directory
      run: tar -xzf wave.tar.gz -C project_folder --strip-components=1

    - name: Debug - List contents of test directory
      run: |
        echo "Contents of project_folder directory:"
        ls -la project_folder
        echo "Contents of project_folder/public directory (if it exists):"
        ls -la project_folder/public || echo "Public directory not found"

    - name: Run PHP built-in server
      run: |
        cd project_folder
        php -S localhost:8000 -t public &
        echo $! > php_server.pid

    - name: Wait for server to start
      run: sleep 10

    - name: Check if installer page is accessible
      run: |
        response=$(curl -sS -o response.html -w "%{http_code}" http://localhost:8000)
        if [ $response -eq 200 ]; then
          echo "Installer page is accessible"
          cat response.html
        else
          echo "Installer page is not accessible. HTTP status code: $response"
          cat response.html
          exit 1
        fi

    - name: Debug - Check PHP error log
      if: failure()
      run: |
        echo "PHP Error Log:"
        cat /tmp/php_errors.log || echo "No PHP error log found"

    - name: Stop PHP server
      if: always()
      run: kill $(cat project_folder/php_server.pid)

    - name: Check if .env file is created
      run: |
        if [ -f "project_folder/.env" ]; then
          echo ".env file created successfully"
          cat project_folder/.env
        else
          echo ".env file not created"
          exit 1
        fi

    - name: Check if application key is set
      run: |
        if grep -q "APP_KEY=" "project_folder/.env"; then
          echo "Application key is set"
        else
          echo "Application key is not set"
          exit 1
        fi