name: Wave Homepage Check

on:
  workflow_call:
    inputs:
      install-path:
        required: true
        type: string

jobs:
  check-homepage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug install path
      run: |
        echo "Provided install path: ${{ inputs.install-path }}"
        ls -la ${{ inputs.install-path }} || echo "Provided path does not exist"
        echo "Current directory: $(pwd)"
        ls -la

    - name: Check install path
      run: |
        if [ ! -d "${{ inputs.install-path }}" ]; then
          echo "Error: The specified install path does not exist: ${{ inputs.install-path }}"
          echo "Contents of current directory:"
          ls -la
          echo "Contents of /home/runner/work/wave/wave:"
          ls -la /home/runner/work/wave/wave
          exit 1
        fi

    - name: Start Laravel server
      run: |
        cd "${{ inputs.install-path }}" || exit 1
        echo "Current directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        php artisan serve --port=8000 &
        echo $! > laravel_server.pid

    - name: Wait for server to start
      run: |
        for i in {1..30}; do
          if curl -s http://127.0.0.1:8000 > /dev/null; then
            echo "Server is up!"
            break
          fi
          if [ $i -eq 30 ]; then
            echo "Server failed to start after 30 seconds"
            exit 1
          fi
          sleep 1
        done

    - name: Check if homepage is accessible
      run: |
        response=$(curl -sS -o homepage.html -w "%{http_code}" http://127.0.0.1:8000)
        if [ $response -eq 200 ]; then
          echo "Homepage is accessible"
          if grep -q "Ship in Days" homepage.html; then
            echo "Homepage contains expected content"
          else
            echo "Homepage doesn't contain expected content"
            echo "Content of homepage.html:"
            cat homepage.html
            exit 1
          fi
        else
          echo "Homepage is not accessible. HTTP status code: $response"
          echo "Content of homepage.html:"
          cat homepage.html
          exit 1
        fi

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Capture screenshot
      run: |
        wkhtmltoimage http://127.0.0.1:8000 homepage_screenshot.png

    - name: Upload screenshot as artifact
      uses: actions/upload-artifact@v3
      with:
        name: homepage-screenshot
        path: homepage_screenshot.png

    - name: Stop Laravel server
      if: always()
      run: |
        if [ -f "${{ inputs.install-path }}/laravel_server.pid" ]; then
          kill $(cat "${{ inputs.install-path }}/laravel_server.pid")
        else
          echo "No PID file found. Server may not have started correctly."
        fi