name: Wave Manual Installation

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: '8.2'
    outputs:
      install-path:
        description: "The path where Wave is installed"
        value: ${{ jobs.install-wave.outputs.install-path }}

jobs:
  install-wave:
    runs-on: ubuntu-latest
    outputs:
      install-path: ${{ steps.set-path.outputs.path }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: pdo_sqlite
    
    - name: Create project directory
      run: mkdir -p ${{ github.workspace }}/project_folder

    - name: Download tarball of current commit
      run: |
        TARBALL_URL=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      https://api.github.com/repos/${{ github.repository }}/tarball/${{ github.sha }} \
                      -I | grep -i "location:" | cut -d " " -f 2 | tr -d '\r')
        curl -L -o wave.tar.gz $TARBALL_URL

    - name: Extract tarball to project directory
      run: tar -xzf wave.tar.gz -C project_folder --strip-components=1

    - name: Copy .env.example file
      run: |
        cd project_folder
        cp .env.example .env

    - name: Create SQLite database
      run: |
        cd project_folder
        touch database/database.sqlite

    - name: Install Composer Dependencies
      run: |
        cd project_folder
        composer install

    - name: Generate application key
      run: |
        cd project_folder
        php artisan key:generate

    - name: Database Migrations and Seed
      run: |
        cd project_folder
        php artisan migrate
        php artisan db:seed

    - name: Set and output install path
      id: set-path
      run: |
        INSTALL_PATH="${{ github.workspace }}/project_folder"
        echo "path=$INSTALL_PATH" >> $GITHUB_OUTPUT
        echo "Wave installed at: $INSTALL_PATH"
        ls -la $INSTALL_PATH